spring:
  application:
    name: studyflash

  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  secret: minha-chave-super-secreta-para-jwt-256-bits-library-api
  expiration: 86400000